### ISSUE TITLE
firebase-client-init.js being called on server

### ISSUE THREAD

**Issue by chrishutchison9** [davidroyer/nuxt-ssr-firebase-auth#2]
Reproduce while in dev mode by introducing 

console.log('test');

in firebase-client-init.js then saving. You will see it outputted in the system console.

**Comment by fredski02** [comment]
Why is it bad that you can console.log('test') in this file exactly? Ive been copying parts of this set up for a couple of days so id like to know.

**Comment by chrishutchison9** [comment]
I don't think there's anything necessarily bad about it, it was probably intended but the name of the file could be confusing and lead devs to believe it's only called on the client.

**Comment by fredski02** [comment]
Ah, i see your point, i guess the intention here was that sometimes developers call an initialized interface like firebase a client as it acts as a client API to its consumer at the firebase servers etc. But yeah i agree lol, it should really just be firebase-sdk.js, fb-config.js, fb-connect.js
